gestion.abs.iutbm.:
    resource: "@Gestion_Abs_IUTBM_Bundle/Controller/"
    type:     annotation
    prefix:   /

abs:
    type:     rest
    resource: Gestion_Abs_IUTBM_Bundle\Controller\AbscenceController
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
   path: /logout