security: 
  access_control: 
    - 
      path: ^/user
      roles: ROLE_USER
  firewalls: 
    dev: 
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main: 
      anonymous: ~
      http_basic_ldap: 
        dn_string: "uid={username},ou=people,dc=univ-fcomte,dc=fr"
        service: ldap
  providers: 
    in_memory: 
      memory: ~
    my_ldap: 
      ldap: 
        base_dn: "dc=univ-fcomte,dc=fr"
        default_roles: ROLE_USER
        search_dn: null
        search_password: null
        service: ldap
        filter: (uid={username})
        uid_key: uid

