security: 
  access_control: 
    - 
      path: ^/user
      roles: ROLE_USER
  firewalls: 
    dev: 
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      logout:
          path:   /logout
          target: /
      form_login:
         login_path: login
         check_path: login
      guard:
         authenticators:
             - ldap_auth

  providers: 
    in_memory: 
      memory: ~
    our_db_provider:
      entity:
         class: Gestion_Abs_IUTBM_Bundle:User
         property: uid