security: 
  access_control: 
    - 
      path: ^/user
      roles: ROLE_USER
  firewalls: 
    dev: 
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main: 
      anonymous: ~
      simple_form:
          authenticator: ldap_auth
          check_path:    login
          login_path:    login
  providers: 
    in_memory: 
      memory: ~
    webservice:
      id: app.webservice_user_provider
   