# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    ldap:
        class: 'Symfony\Component\Ldap\LdapClient'
        arguments:
            - localhost   # host
            - 9999         # port
      
    ldap_auth:
        class:     Gestion_Abs_IUTBM_Bundle\Security\LdapAuthenticator
        arguments: ["@security.password_encoder"]
        
    app.webservice_user_provider:
        class: Gestion_Abs_IUTBM_Bundle\Security\LdapProviderInterface