<?php

namespace Gestion_Abs_IUTBM_Bundle\Repository;

/**
 * JustificatifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustificatifRepository extends \Doctrine\ORM\EntityRepository
{
}
